# Generated by Django 2.1.5 on 2019-01-24 13:26

from django.db import migrations, models
import entities.models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
        migrations.AddField(
            model_name='entity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=entities.models.upload_image),
        ),
    ]
